spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/courier_tracking
    username: tracker
    password: password
  kafka:
    bootstrap-servers: kafka:29092
  redis:
    host: redis
    port: 6379

application:
  kafka:
    topics:
      location-events: courier-locations
  cache:
    ttl-seconds: 3600