spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/courier_tracking
    username: tracker
    password: password
  kafka:
    bootstrap-servers: kafka:29092

application:
  kafka:
    topics:
      location-events: courier-locations
